[production]
app-server ansible_host=172.31.17.124 ansible_user=ubuntu

[production:vars]
ansible_ssh_private_key_file=~/.ssh/ansible_key
ansible_python_interpreter=/usr/bin/python3
app_port=8000
container_port=8000
